# Example template

qqbot-name: TestBot  # optional
cqhttp-url: 'ws://127.0.0.1:5700/'

groups:           # optional
  - debug:
    alias: DEBUG  # optional
    group-id: 123456789
    listen: true  # 是否监听此群聊
    post: true    # 是否把消息发送到此群聊
  - main:
    group-id: 987654321
    listen: false
    post: false

friends:          # optional
  - he:
    user-id: 123456709
    listen: true
    post: true
  - she:
    user-id: 907654321
    listen: false
    post: false

multichat-url: 'ws://127.0.0.1:6780/'
multichat-key: 'password'